name: tp1
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0' # Ensuring compatibility

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7 # Ensure correct package version
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/pic.JPG  # Corrected path
    - asset/logo.png  # Corrected path
